global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'webac'
    static_configs:
      - targets: ['35.209.212.46:5002']

  - job_name: 'webac-replica1'
    static_configs:
      - targets: ['35.209.212.46:5005']

  - job_name: 'webac-replica2'
    static_configs:
      - targets: ['35.209.212.46:5006']

  - job_name: 'your_vm'
    static_configs:
      - targets: ['35.209.212.46:5001']

  - job_name: 'replica1-prime'
    static_configs:
      - targets: ['35.209.212.46:5003']
  - job_name: 'replica2-prime'
    static_configs:
      - targets: ['35.209.212.46:5004']
